# ==> Install Fussion Middleware Infrastructure
---

- name: Copy file for silent installation
  template: src=silent.xml dest={{ installer_home }}

- name: Execute WebLogic installer
  command: "{{ jdk_home }}/bin/java {{ mw_installer_mem_arg }} -jar {{ software_folder }}/{{ mw_installer }} -mode=silent -silent_xml={{ installer_home }}/silent.xml -log={{ installer_home }}/{{ log_prefix }}.install.log -silent_log={{ installer_home }}/{{ log_prefix }}.install.silent.log"
