# ==> Create new domain, set java mem args for the admin server, init security for the admin server
---

- name: Copy create domain script
  template: src=create-domain.py dest={{ installer_home }}

- name: Execute create domain script
  shell: "{{ weblogic_home }}/common/bin/wlst.sh {{ installer_home }}/create-domain.py"

- name: Insert USER_MEM_ARGS in setDomainEnv.sh
  blockinfile:
    path: "{{ domain_home }}/bin/setDomainEnv.sh"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: "export WL_HOME"
    block: |
      USER_MEM_ARGS="{{ domain_user_mem_arg }}"
      export USER_MEM_ARGS
    backup: yes

- name: Create security folder on Admin Server
  file: state=directory path={{ domain_home }}/servers/{{ admin_server_name }}/security

- name: Create boot.properties file
  template: src=boot.properties dest={{ domain_home }}/servers/{{ admin_server_name }}/security/
