---

# ==> Upgrade all packages
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

# ==> Install some packages, mainly used for the wls automation demo
- name: Install tree
  yum:
    name:
      - tree
      - unzip
    state: present

# ==> Create user and group
- name: Create group
  group: name={{ oracle_group }} state=present
- name: Create user
  user: name={{ oracle_user }} group={{ oracle_group }} password={{ oracle_os_user_pass }}

# ==> Create tmp directory to be used as remote_tmp path. Used by blockinfile module.
- name: Create tmp ansible directory for oracle_user
  file: state=directory path="/tmp/ansible-{{ oracle_user }}" owner={{ oracle_user }} group={{ oracle_group }} mode=0700

# ==> Create Base Directories
- name: Create Middleware Home directory
  file: state=directory path={{ middleware_home }} owner={{ oracle_user }} group={{ oracle_group }}
- name: Create Domains Home directory
  file: state=directory path={{ domains_home }} owner={{ oracle_user }} group={{ oracle_group }}
- name: Create Applications Home directory
  file: state=directory path={{ applications_home }} owner={{ oracle_user }} group={{ oracle_group }}
- name: Create Installer Home directory
  file: state=directory path={{ installer_home }} owner={{ oracle_user }} group={{ oracle_group }}

# ==> Install JDK package
- name: Install JDK rpm from local file
  yum:
    name: "{{ software_folder }}/{{ jdk_installer }}"
    state: present
